### ISSUE TITLE
missing \fi in .sty file

### ISSUE THREAD

**Issue by marisacasillas** [rlevy/cogsci-template#2]

**Comment by marisacasillas** [comment]
hello! if you uncomment the line in the latex template to generate a "final version" of the document, you get an error. i think it's just a missing \fi that should go on line 129 of the style file.

**Comment by mcfrank** [comment]
is this fixed by https://github.com/rlevy/cogsci-template/pull/1?

**Comment by marisacasillas** [comment]
yup! thanks.
